### ISSUE TITLE
3.6 bind is broken

### ISSUE THREAD

**Issue by byrnedo** [jamesridgway/mongo-tmpfs#1]
Hi, 

` --bind_ip 0.0.0.0` needs to be added for 3.6 to work

**Comment by jamesridgway** [comment]
Thanks for reporting this, pull request #2  shows the fix for this issue.

**Comment by jamesridgway** [comment]
The image for jamesridgway/mongo-tmpfs:3.6 has now been updated:

https://hub.docker.com/r/jamesridgway/mongo-tmpfs/
